"use client";

import './globals.css';
import { Inter } from 'next/font/google';

// Note: MDB Integration...!
import 'mdb-react-ui-kit/dist/css/mdb.min.css';
import "@fortawesome/fontawesome-free/css/all.min.css";

// Note: Importing required components...!
import Navigation from './components/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />

        {children}
      </body>
    </html>
  );
};

export default RootLayout;